server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/simpledemo.p12
    key-store-password: simpledemo.sp
    key-alias: simpledemo
    enabled: false
  port: 8080
#  originhttp:
#    port: 8080

spring:
  application:
    name: simple-e-commerce-v3
  profiles:
    active: dev
  #  Below config will make 404 page show as a restful json response.
  #  But the side effects is that the static resource will not able to display, so disable this
  #  web:
  #    resources:
  #      add-mappings: false
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB #Size limit for a single file. The maximum allowed size of a single uploaded file. i.e. 1MB Priority 2, This config also works for limit the upload Maximum size.
      max-request-size: 100GB #Each request total file size limit. The maximum allowed size of a complete request. i.e. 100KB Priority 1, Limit the multipart/form-data file upload Maximum size.

  datasource:
    fst:
      url: jdbc:h2:mem:ecommercedb;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      initialization-mode: embedded
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    snd:
      url: jdbc:h2:mem:snd;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      initialization-mode: embedded

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
      trace: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  cache:
    type: jcache
    jcache:
      config: classpath:/ehcache3.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: ps.demo.entity

---

spring:
  config:
    activate:
      on-profile: dev
  #  datasource:
  #    url: jdbc:h2:mem:ecommercedb
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #    initialization-mode: embedded
  sql:
    init:
      encoding: utf-8
      schema-locations: classpath:schema_h2.sql
      data-locations: classpath:data_h2.sql
      mode: always

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop # Hibernate ddl auto (create, create-drop, validate, update)

#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: ps.demo.entity



