[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 生存，繁衍
> align=`center`


## 竞争
> leftSide=`true`


### 嫉妒

### 自私

### 争强好胜

### 专权

## 合作

### 社交

### 归属，联盟

### 共情

### 从众

### 互惠

#### 面子效应

### 社会认同

### 权威，规则

#### 顺从

#### 逆反

### 熟悉

#### 重复曝光

## 懒惰

### 心理捷径

#### 偏见

#### 锚定效应

#### 情感启发

#### 代表性启发

#### 可得性启发

## 好奇心，求知欲
> leftSide=`true`


## 贪婪
> leftSide=`true`


## 恐惧
> leftSide=`true`


### 损失厌恶

#### 沉没成本

### 稀缺效应

## 安全感
> leftSide=`true`


### 一致性

### 确定性

## 逐利
> leftSide=`true`


## 奖励
> leftSide=`true`


### 喜乐

## 惩罚

### 悲愤

## 情感
