// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Training.proto

// Protobuf Java Version: 3.25.3
package ps.demo.protobuf.model;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string course_name = 2;</code>
   * @return The courseName.
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 2;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated .Student student = 3;</code>
   */
  java.util.List<ps.demo.protobuf.model.Student> 
      getStudentList();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  ps.demo.protobuf.model.Student getStudent(int index);
  /**
   * <code>repeated .Student student = 3;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  java.util.List<? extends ps.demo.protobuf.model.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .Student student = 3;</code>
   */
  ps.demo.protobuf.model.StudentOrBuilder getStudentOrBuilder(
      int index);
}
