---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-e-commerce-v3
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-e-commerce-v3
  template:
    metadata:
      labels:
        app: simple-e-commerce-v3
    spec:
      containers:
        - name: simple-e-commerce-v3
          image: "xxx.com/path/repo/simple-e-commerce-v3:THE_APP_VERSION"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: APPID
              valueFrom:
                secretKeyRef:
                  name: simple-e-commerce-v3-key
                  key: appid
            - name: APPSECRET
              valueFrom:
                secretKeyRef:
                  name: simple-e-commerce-v3-key
                  key: appsecret
          volumeMounts:
            - name: myvolume
              mountPath: /app/volume
              readOnly: true
      volumes:
        - name: myvolume
          secret:
            secretName: simple-e-commerce-v3-key
#            items:
#              - key: key.pem
#                path: key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: simple-e-commerce-v3-service
  namespace: app
  labels:
    app: simple-e-commerce-v3
spec:
  ports:
    - port: 8080 # between containers for service call for K8s
      targetPort: 8080 # container port
      nodePort: 30080 # by default >30000 for external call
  type: NodePort
  selector:
    app: simple-e-commerce-v3

---
apiVersion: v1
kind: Secret
metadata:
  name: simple-e-commerce-v3-key
type: Opaque
data:
  appid: QVBQMTIzNA==
  appsecret: UGFzc3dkXzEyMzQ1Ng==
  key.pem: VGhpcyBpcyB0aGUgZGF0YSBmcm9tIGtleS5wZW0gZmlsZSBmcm9tIHNlY3JldApnb29kIGx1Y2t+Cl9fa3ViZXJuZXRzIHNlY3JldHM=
